<!DOCTYPE html>
<div id="page-content-wrapper">
    <div class="container-fluid">
        
        <center><h1><u>Informations générales</u></h1></center><br>
        
        <table class="table table-striped table-bordered">
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Logo</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <img 
                        style = "width:200px; height:200px;" 
                        src   = "data:image/<?php echo $this->name_logo . ' ;base64,' . $this->logo ?>" 
                    />
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Logo</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <img 
                        style = "width:50px; height:50px;" 
                        src   = "data:image/<?php echo $this->name_favicon . ' ;base64,' . $this->favicon ?>" 
                    />
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Phrase d'accroche</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <?php echo $this->resultat['catchphrase'] ?>
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Facebook</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <a target=_blank" href="<?php echo $this->resultat['link_facebook'] ?>">
                        <?php echo $this->resultat['link_facebook'] ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Twitter</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <a target=_blank" href="<?php echo $this->resultat['link_twitter'] ?>">
                        <?php echo $this->resultat['link_twitter'] ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Email</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <?php echo $this->resultat['website_email'] ?>
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Téléphone</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <?php echo $this->resultat['website_phone'] ?>
                </td>
            </tr>
            <tr>
                <td style="width:50%; border-right:none;">
                    <strong>Adresse</strong>
                </td>
                <td style="width:50%; border-right:none;">
                    <?php echo $this->resultat['website_address'] ?>
                </td>
            </tr>
        </table>
        
        <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'website', 'action' => 'update'), null, true) ?>">
            Modifier
        </a>
        
    </div>
</div>