<!DOCTYPE html>
<div id="page-content-wrapper">
    <div class="container-fluid">
        
        <center><h1><u>Liste des sliders</u></h1></center><br>
        
        <table class="table table-striped table-bordered">
            <tr>
                <td style="width:30%;">
                    <strong>Adresse URL</strong>
                </td>
                <td style="width:30%;">
                    <strong>Actif</strong>
                </td>
                <td style="width:30%; border-right:none;">
                    <strong>Position</strong>
                </td>
                <td style="width:10%; border:none;"></td>
            </tr>
        </table>
        
        <?php foreach($this->resultat as $resultat) : ?>
        
            <table class="table table-striped table-bordered">
                <tr>
                    <td style="width:30%;">
                        <?php echo $resultat['url']; ?>
                    </td>
                    <td style="width:30%;">
                        <?php 
                            
                            if($resultat['is_active'] == 1) {
                                
                                echo 'Oui';
                            } 
                            else {
                                
                                echo 'Non';
                            }
                            
                        ?>
                    </td>
                    <td style="width:30%; border-right:none;">
                        <?php echo $resultat['position']; ?>
                    </td>
                    <td style="width:10%; border:none;">
                        <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'slider', 'action' => 'update', 'id' => $resultat['id']), null, true) ?>">
                            Modifier
                        </a>
                    </td>
                </tr>
            </table>

        <?php endforeach;  ?>
        
    </div>
</div>